const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
const ERROR_FETCHING_WEATHER_DATA = 'ERROR_FETCHING_WEATHER_DATA';
const LOADING_WEATHER_DATA = 'LOADING_WEATHER_DATA';
const SET_FILTERED_DATA = 'SET_FILTERED_DATA';

export {
    FETCH_WEATHER_DATA,
    ERROR_FETCHING_WEATHER_DATA,
    SET_FILTERED_DATA,
    LOADING_WEATHER_DATA,
}